### ISSUE TITLE
Issues with XML and html/template

### ISSUE THREAD

**Issue by enrichman** [italia/spid-go#1]
SP Metadata are not correctly parsed since the `html/template` package is not meant for XML templating (see: https://github.com/golang/go/issues/3133 )
It results in having the first line escaped in
```
&lt;?xml version="1.0"?>
```

I would suggest to delegate the SAML XML logic to a more complete and robust library implementation, such as https://github.com/RobotsAndPencils/go-saml.

What do you think? 👍

**Comment by alranel** [comment]
Thank you for the report! Switched to text/template which does not provide XML escaping but it's fine for our needs.

The SAML package you linked actually looks abandoned, and generates invalid metadata: https://github.com/RobotsAndPencils/go-saml/issues/9
